### ISSUE TITLE
Build with stack 

### ISSUE THREAD

**Issue by joprice** [evincarofautumn/kitten#154]
I'd like to play around with kitten, but I have trouble running anything with cabal. Stack has liberated the haskell community from cabal hell. It would be nice to setup a stack.yml for the project.

**Comment by evincarofautumn** [comment]
Sure, will do. I’ve been meaning to do this anyway.

In the meantime, the Makefile sets up a Cabal sandbox appropriately, so everything should Just Work as long as you’re using `cabal-install` ≥1.22. If you encounter https://github.com/haskell/cabal/issues/2320, you may need to delete `dist` and `.cabal-sandbox` if they were created with an older version of Cabal.

**Comment by evincarofautumn** [comment]
Added a basic `stack.yaml` in 9c64fca9f72612e4d1c95df853c18197953546d0.

I would need to update the Makefile if Stack is to be the default build tool, because `make` also runs integration tests, but I’ll hold off for now because I’ll probably convert those to unit tests in the [new compiler](https://github.com/evincarofautumn/kitten/pull/152) and nix `make`.

**Comment by joprice** [comment]
I was able to build via stack. Thanks!
