### ISSUE TITLE
Explicit dependancy for fail?

### ISSUE THREAD

**Issue by george-b** [evincarofautumn/kitten#217]
Following the README steps of running `stack steup` then `stack build` I get the following error.

```
~/src/kitten: stack build

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for Kitten-0.1.0.0:
    fail needed, but the stack configuration has no specified version  (latest matching version is 4.9.0.0)
needed since Kitten is a build target.

Some different approaches to resolving this:

  * Recommended action: try adding the following to your extra-deps in /Users/gbrown/src/kitten/stack.yaml:

- fail-4.9.0.0@sha256:35d1ee29364447c1b7d616bb1ee31f162b73e85fea91d7ca6441cf901398f572,1051

Plan construction failed.
```

I don't know much about Haskell packaging but I'm guessing this is due to my rather new and barren install.

Adding the following allows the build to run, but I've no idea if it's the right thing to do.

```diff
diff --git a/stack.yaml b/stack.yaml
index ed928ac..2f8b230 100644
--- a/stack.yaml
+++ b/stack.yaml
@@ -1,6 +1,7 @@
 resolver: lts-5.2
 packages:
 - '.'
-extra-deps: []
+extra-deps:
+- fail-4.9.0.0
 flags: {}
 extra-package-dbs: []
```

**Comment by evincarofautumn** [comment]
Ah, I figure this is bitrot caused by the [`MonadFail` proposal](https://wiki.haskell.org/MonadFail_Proposal). I think your patch is the right thing to do here, but I’ll double-check that. Thanks for your help!

I’m doing development in another repo at the moment, and planning to merge them at some point, so this code isn’t really maintained, although it will give you a general idea of the language (and several pesky fundamental bugs, which are what led to Yet Another Rewrite).

**Comment by evincarofautumn** [comment]
Added this patch in a5301fe24dbb9ea91974abee73ad544156ee4722.
